# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_INTEGRATOR:  [ROLE_USER]
        ROLE_API_USER:    [ROLE_USER]
        ROLE_ADMIN:       [ROLE_INTEGRATOR, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
                id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/dashboard/api/v1/
            guard:
                authenticators:
                    - app.jwt_token_authenticator

        main:
            anonymous: true
            # activate different ways to authenticate
            logout: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }

    encoders:
        AppBundle\Entity\User: sha512